name: lx/template

autoload:
  psr-4:
    lx\template\:
      - ''
      - src
    lx\template\sys\: '.system'

service:
  class: lx\template\Service

  routes:
    /: '' #TODO: must be defined

  plugins: plugins
  components:
    jsCompiler: lx\template\JsCompiler
